### ISSUE TITLE
Capitalizes letter after apostrophe

### ISSUE THREAD

**Issue by rl421403** [tommcfarlin/title-capitalization-for-wordpress#11]
Plugin makes letter after apostrophe capitalize.

It's -> It'S

Should not do that,

**Comment by tommcfarlin** [comment]
Thank you, sir - nice catch. When I revisit the plugin, I'll patch that up!

**Comment by rl421403** [comment]
Great!

It's a useful plugin. I am planning to use it but I kind of do not want the option to auto capitalize header titles in content. Is it possible to turn this off?

**Comment by tommcfarlin** [comment]
Right now, no. It's just a matter of when the plugin is on or off.

**Comment by paulshryock** [comment]
Hey Tom, this is a great plugin. Thanks for making it!

I am using WordPress 4.3 and Title Capitalization for WordPress v1.1.4 and until recently, the letters after apostrophes behaved correctly.

Today is the first time I've written a post while using this plugin since the WP 4.3 update, and I noticed that letters after apostrophes are capitalizing incorrectly again, as they did in old versions of the plugin.

Are you experiencing this as well?

![apostrophe-caps](https://cloud.githubusercontent.com/assets/7530507/9534832/745bfa22-4ce9-11e5-8cca-e00bb261a7fe.jpg)

**Comment by afragen** [comment]
I just tested using the current master branch and it seems to be working here.

Before selecting 'Update'
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/9536521/c23c6252-4ce1-11e5-8f07-362b4d9ac59c.png)

After selecting 'Update'
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/9536524/cc2b97ec-4ce1-11e5-9411-e7031818549b.png)

FWIW, I'm using latest 4.4alpha

**Comment by paulshryock** [comment]
Must be my configuration. Thanks for checking.

**Comment by tommcfarlin** [comment]
@paulshryock Are you still experiencing this? If so, let me know; otherwise, did you find anything odd in your configuration that you changed to get it working?

Let me know - would love to have this documented.

**Comment by afragen** [comment]
All I could say was it seems to be working for me.
